### ISSUE TITLE
The text field does not become empty when the "Add New Task" button is clicked.

### ISSUE THREAD

**Issue by ThierryRakotomanana** [ThierryRakotomanana/kanban-js#6]
#### Description
After creating a task, The text field does not become empty when the "Add New Task" button is clicked.

#### Screenshots
![Issue 02](https://github.com/ThierryRakotomanana/kanban-js/assets/105288252/0c702d44-232f-4b42-8652-6f656cf50a08)

#### Tasks
This may help you to fix these bugs , it's just a suggestion but if you find better code, don't hesitate to .send it in PR, by referencing this issue(#6).

In the `app.js` file, in the function `createNewTask` 
```javascript
const createNewTask = () => {
```
- [ ] Set the value of `taskTitle` to empty string
- [ ] Send PR(Pull Request) by following the [Contributing Guidelines](https://github.com/ThierryRakotomanana/kanban-js/blob/main/contributing.md)

**Comment by jonichi16** [comment]
Hi, can I work with this? Thank you

**Comment by ThierryRakotomanana** [comment]
Hi @jonichi16, thank you for your interest! And yes, of course you can work on it
